// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfsRLR6l5e13Jto5dtpks51YTG4p2m5AA',
    appId: '1:805798065244:web:06861b033b39e884a86299',
    messagingSenderId: '805798065244',
    projectId: 'real-time-tracking-971b0',
    authDomain: 'real-time-tracking-971b0.firebaseapp.com',
    storageBucket: 'real-time-tracking-971b0.appspot.com',
    measurementId: 'G-DE9H6D2BK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg-7Y2iwFpWBSUMKzywT_G3A8Bm2bVi3c',
    appId: '1:805798065244:android:c749a095570cbcb2a86299',
    messagingSenderId: '805798065244',
    projectId: 'real-time-tracking-971b0',
    storageBucket: 'real-time-tracking-971b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW7wOrRKI1B0gObkk8va3O8n_UB9cZaJE',
    appId: '1:805798065244:ios:3695bd8533edc8dba86299',
    messagingSenderId: '805798065244',
    projectId: 'real-time-tracking-971b0',
    storageBucket: 'real-time-tracking-971b0.appspot.com',
    iosBundleId: 'com.example.vidyutkranti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW7wOrRKI1B0gObkk8va3O8n_UB9cZaJE',
    appId: '1:805798065244:ios:7be342d10baf9128a86299',
    messagingSenderId: '805798065244',
    projectId: 'real-time-tracking-971b0',
    storageBucket: 'real-time-tracking-971b0.appspot.com',
    iosBundleId: 'com.example.vidyutkranti.RunnerTests',
  );
}
